imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        console:
            type:   console
            bubble: false
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

assetic:
    use_controller: true

#swiftmailer:
#    delivery_address: me@example.com

services:
    user_service:
        class: Reports\UserBundle\Controller\UserController
        calls:
            - [setContainer, ["@service_container"]]
    profile_service:
        class: Reports\DashboardBundle\Controller\ProfileController
        calls:
            - [setContainer, ["@service_container"]]     
    personel_service:
        class: Reports\DashboardBundle\Controller\PersonelController
        calls:
            - [setContainer, ["@service_container"]]
    reports_service:
        class: Reports\DashboardBundle\Controller\ReportsController
        calls:
            - [setContainer, ["@service_container"]]
    reports_common_konsultant:
        class: Reports\ReportsBundle\Controller\KonsultantController
        calls:
            - [setContainer, ["@service_container"]]
    reports_raabe_efficiency:
        class: Reports\ReportsBundle\Controller\Raabe\EfficiencyController
        calls:
            - [setContainer, ["@service_container"]]
    reports_raabe_status_group:
        class: Reports\ReportsBundle\Controller\Raabe\StatusGroupController
        calls:
            - [setContainer, ["@service_container"]]
    