imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

services:
    user_service:
        class: Reports\UserBundle\Controller\UserController
        calls:
            - [setContainer, ["@service_container"]]
    profile_service:
        class: Reports\DashboardBundle\Controller\ProfileController
        calls:
            - [setContainer, ["@service_container"]]     
    personel_service:
        class: Reports\DashboardBundle\Controller\PersonelController
        calls:
            - [setContainer, ["@service_container"]]
    reports_service:
        class: Reports\DashboardBundle\Controller\ReportsController
        calls:
            - [setContainer, ["@service_container"]]
    schedule_service:
        class: Reports\DashboardBundle\Controller\ScheduleController
        calls:
            - [setContainer, ["@service_container"]]
    reports_raabe_konsultant:
        class: Reports\ReportsBundle\Controller\Raabe\KonsultantController
        calls:
            - [setContainer, ["@service_container"]]
    reports_wip_konsultant:
        class: Reports\ReportsBundle\Controller\WIP\KonsultantController
        calls:
            - [setContainer, ["@service_container"]]
    reports_raabe_efficiency:
        class: Reports\ReportsBundle\Controller\Raabe\EfficiencyController
        calls:
            - [setContainer, ["@service_container"]]
    reports_raabe_status_group:
        class: Reports\ReportsBundle\Controller\Raabe\StatusGroupController
        calls:
            - [setContainer, ["@service_container"]]
    reports_raabe_ik_all_rabat:
        class: Reports\ReportsBundle\Controller\Raabe\IKAllRabatController
        calls:
            - [setContainer, ["@service_container"]]
    reports_wip_status_group:
        class: Reports\ReportsBundle\Controller\WIP\StatusGroupController
        calls:
            - [setContainer, ["@service_container"]]
    reports_supermemo_daily_operations:
        class: Reports\ReportsBundle\Controller\Supermemo\DailyOperationsController
        calls:
            - [setContainer, ["@service_container"]]
    reports_supermemo_statuses:
        class: Reports\ReportsBundle\Controller\Supermemo\StatusesController
        calls:
            - [setContainer, ["@service_container"]]
    reports_wsfinance_consultant:
        class: Reports\ReportsBundle\Controller\WSFinance\ConsultantController
        calls:
            - [setContainer, ["@service_container"]]
    reports_wsfinance_operations:
        class: Reports\ReportsBundle\Controller\WSFinance\DailyOperationsController
        calls:
            - [setContainer, ["@service_container"]]
    reports_wsfinance_statuses:
        class: Reports\ReportsBundle\Controller\WSFinance\StatusesController
        calls:
            - [setContainer, ["@service_container"]]
    reports_common_operations:
        class: Reports\ReportsBundle\Controller\Common\DailyOperationsController
        calls:
            - [setContainer, ["@service_container"]]
    reports_ing_leads:
        class: Reports\ReportsBundle\Controller\ING\LeadsController
        calls:
            - [setContainer, ["@service_container"]]
    reports_aig_statuses:
        class: Reports\ReportsBundle\Controller\AIG\StatusesController
        calls:
            - [setContainer, ["@service_container"]]
    reports_aig_contact:
        class: Reports\ReportsBundle\Controller\AIG\ContactController
        calls:
            - [setContainer, ["@service_container"]]
    reports_klimuszko_statuses:
        class: Reports\ReportsBundle\Controller\Klimuszko\StatusesController
        calls:
            - [setContainer, ["@service_container"]]
    reports_vivi_statuses:
        class: Reports\ReportsBundle\Controller\Vivi\StatusesController
        calls:
            - [setContainer, ["@service_container"]]
    reports_vivi_konsultant:
        class: Reports\ReportsBundle\Controller\Vivi\KonsultantController
        calls:
            - [setContainer, ["@service_container"]]