parameters:
    database_driver: pdo_pgsql
    database_host: 192.168.20.2
    database_port: 5432
    database_name: Alfavox
    database_user: sparrow
    database_password: 5p4rr0w
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: pl
    secret: 2f42d954e6da32e33ac817dde3237a62045b4fa0
    database_path: null
