reports_dashboard:
    resource: "@ReportsDashboardBundle/Controller/"
    type:     annotation
    prefix:   /

reports_user:
    resource: "@ReportsUserBundle/Controller/"
    type:     annotation
    prefix:   /

reports_auth:
    resource: "@ReportsAuthBundle/Controller/"
    type:     annotation
    prefix:   /
    
login:
    path:      /login
    defaults:  { _controller: ReportsUserBundle:User:login }

logout:
    path:      /logout
    defaults:  { _controller: ReportsUserBundle:User:logout }
    
dashboard:
    path: /dashboard/{page}
    defaults: { _controller: ReportsDashboardBundle:Default:index }

